[package]
name = "ttv"
version = "0.3.0"
authors = ["Ben Sully <ben@bsull.io>"]
edition = "2018"

[dependencies]
clap = { version = "2.33.1", features = ["yaml"] }
csv = "1.1.3"
env_logger = "0.7.1"
flate2 = "1.0.14"
indicatif = "0.14.0"
jemallocator = "0.3.2"
log = "0.4.8"
rand = "0.7.3"
rand_chacha = "0.2.2"
rayon = "1.3.0"
structopt = "0.3.14"
try_from = "0.3.2"
